language: php
sudo: required

before_install:
  - cd http

before_script:
  - cd http

install:
  - composer self-update
  - composer-install --no-interaction
script:
  - phpunit --configuration phpunit.xml